[WIP]enabling IPCC module of the stm32WB55
stm32duino/Arduino_Core_STM32 pull request #1191
Opened 2020-09-25 11:48 UTC by FRASTM

This PR is the introduction  of the BLE for the stm32WB55 

It requires the

2020-10-30 10:07 UTC, fpistm commented on variants/PNUCLEO_WB55RG/variant.cpp
> +#if  defined (ARDUINO_PNUCLEO_WB55RG)
You don't need to use this define, it is always true as it is in the variant.

2020-11-09 09:22 UTC, fpistm requested changes
In addition to my review comments, please:
- Rebase and squash on top of the master and change commit message to something like:

> [PNUCLEO_WB55RG] BLE support configuration
> 
> - Enable IPCC HAL module
> - Manage OTP to ...
> - Update clock configuration
> 

- Apply astyle (script available in CI/astyle/astyle.py)

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/otp.h
> +  {
No need to define this as Arduino only manage one toolchain.
Moreover the packed attribute does not need to be redefined. It is already managed here:
https://github.com/stm32duino/Arduino_Core_STM32/blob/bee856121e7406314226506d20617b523a092a70/system/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_def.h#L115

```suggestion
  typedef struct __packed {
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/otp.h
> +  /* Exported functions ------------------------------------------------------- */
```suggestion
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/otp.h
> +#define CFG_OTP_END_ADDRESS      OTP_AREA_END_ADDR
```suggestion
#define CFG_OTP_END_ADDRESS     OTP_AREA_END_ADDR
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/variant.cpp
> +    RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
Avoid **_-Wmissing-field-initializers_** warning
```suggestion
    RCC_OscInitTypeDef RCC_OscInitStruct = {};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
    RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {};
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/variant.cpp
> +    return;
```suggestion
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/variant.cpp
> +    while (LL_HSEM_1StepLock(HSEM, CFG_HW_CLK48_CONFIG_SEMID)); */
Remove if not needed
```suggestion
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/variant.cpp
> +    */
```suggestion
    /* Configure the SYSCLKSource, HCLK, PCLK1 and PCLK2 clocks dividers */
```

2020-11-09 09:22 UTC, fpistm commented on variants/PNUCLEO_WB55RG/variant.h
> +
Remove extra line
```suggestion
```

2020-11-09 10:01 UTC, FRASTM commented
fix according to the review (mainly astyle)
squash in one commit

2020-11-09 10:56 UTC, fpistm requested changes

2020-11-09 10:56 UTC, fpistm commented on variants/PNUCLEO_WB55RG/otp.h
> +
Useless can be removed

```suggestion
/* Exported types ------------------------------------------------------------*/
```

2020-11-10 08:47 UTC, fpistm approved these changes
LGTM
Thanks @FRASTM

2020-11-30 15:23 UTC, merged