Fix two assert_param calls.
stm32duino/Arduino_Core_STM32 pull request #1242
Opened 2020-11-29 08:55 UTC by ghent360

Running Marlin with USE_FULL_ASSERT defined as 1 revealed 2 asserts:

assert_param(IS_TIM_CC1_INSTANCE(htim->Instance));

while using TIM7 for TIMER_SERVO on STM32F407 - switched to TIM14

  assert_param(IS_I2C_OWN_ADDRESS2(hi2c->Init.OwnAddress2));

default value was filled as 0xff from twi.c, changed to even value 0xfe.

2020-11-30 13:12 UTC, ABOSTM requested changes
Hi @ghent360 
Thanks for this pull request.
I have 2 remarks about your fix, see inline.

2020-12-01 07:21 UTC, ghent360 commented on libraries/Wire/src/utility/twi.c
> +        handle->Init.OwnAddress2     = 0xFE;
Fixed.

2020-12-01 07:22 UTC, ghent360 commented on variants/PRNTR_Vx/variant.h
> +#define TIMER_SERVO             TIM14
Reverted back to TIM7. Will wait the fix for #1244.

2020-12-01 07:29 UTC, ABOSTM approved these changes
LGTM

2020-12-01 08:39 UTC, merged