add new stm32 nucleo l552ze board
stm32duino/Arduino_Core_STM32 pull request #1256
Opened 2020-12-04 10:10 UTC by FRASTM

add the new **NUCLEO-L552ZE-Q**
STM32 Nucleo-144 development board with STM32L552ZE MCU, SMPS, supports Arduino, ST Zio and morpho connectivity  144 hardware supporting the stm32L5552ZE device.

See [NUCLEO-L552ZE-Q](https://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-mpu-eval-tools/stm32-mcu-mpu-eval-tools/stm32-nucleo-boards/nucleo-l552ze-q.html)
Requires the https://github.com/stm32duino/Arduino_Core_STM32/pull/1249

Signed-off-by: Francois Ramu francois.ramu@st.com

2020-12-09 10:13 UTC, FRASTM commented
Fix I2C pins : SDA on PB9 and SCL on PB8
--> X_NUCLEO_IKS01A3_STTS751_TemperatureLimit.ino  OK

2020-12-09 13:56 UTC, FRASTM commented
tested: SPI_A loopback transfer OK  (A_MISO connected to A_MOSI) with a sample test application

2020-12-15 08:54 UTC, FRASTM commented
rebase
Test EEPROM put/get : passed
Test HWTimer  : passed
Test SerialLoop : passed (with USART3 on pin PD9, PD8)

2020-12-15 14:55 UTC, FRASTM commented
add the support of USB FS : serial CD and Mouse&HID : passed

2021-01-29 17:29 UTC, fpistm requested changes

2021-01-29 17:29 UTC, fpistm commented on cores/arduino/stm32/timer.h
> +#define TIM6_IRQHandler TIM2_DAC_IRQHandler
Why change to `TIM2_DAC_IRQHandler`

2021-01-30 13:45 UTC, fpistm commented on cores/arduino/stm32/timer.h
> +#define TIM6_IRQHandler TIM2_DAC_IRQHandler
Moreover TIM2_DAC_IRQHandler does not exist.

2021-02-01 07:36 UTC, fpistm commented on variants/NUCLEO_L552ZE_Q/variant.cpp
> +
USB clock config is missing

2021-02-01 07:37 UTC, fpistm commented on variants/NUCLEO_L552ZE_Q/variant.h
> +#define PA1_ALT1                113
should be 118, pin numbering is wrong.

2021-02-01 07:37 UTC, fpistm commented on variants/NUCLEO_L552ZE_Q/variant.h
> +#define NUM_DIGITAL_PINS        154
Wrong value

2021-02-01 07:37 UTC, fpistm commented on variants/NUCLEO_L552ZE_Q/variant.h
> +
OSPI missing

2021-02-01 07:39 UTC, fpistm commented on variants/NUCLEO_L552ZE_Q/variant.h
> +#define PB4 25 // SPI_B_MISO
Multiple definition, several warning about that during the compile
// 24 is PA4                   (20)
// 25 is PB4                   (21)

Other pins are also duplcated

2021-02-01 07:40 UTC, fpistm commented on boards.txt
> +Nucleo_144.menu.pnum.NUCLEO_L552ZE_Q.build.cmsis_lib_gcc=arm_cortexM33lf_math
Where are this library ?

2021-02-01 09:24 UTC, fpistm commented
Superseded by #1091

2021-02-01 09:24 UTC, closed without merging