SoftwareSerial stopListening at the begining
stm32duino/Arduino_Core_STM32 pull request #1269
Opened 2020-12-22 09:10 UTC by FRASTM

When begining the transaction, in the SoftwareSerial::begin
, the active_listener is not yet assigned, but null.
Then it differs from _this_ but should not act as if it was listening.

This is the case when testing on nucleo_l552ze board.

2020-12-22 09:24 UTC, fpistm requested changes

2020-12-22 09:24 UTC, fpistm commented on libraries/SoftwareSerial/src/SoftwareSerial.cpp
> +    if (active_listener != 0) {
```suggestion
    if (active_listener != nullptr) {
```

2020-12-22 09:27 UTC, FRASTM commented on libraries/SoftwareSerial/src/SoftwareSerial.cpp
> +    if (active_listener != 0) {
changed

2020-12-22 09:39 UTC, fpistm approved these changes

2021-01-04 10:18 UTC, ABOSTM approved these changes
LGTM

2021-01-04 10:47 UTC, merged