Adding STORM32_V1_31_RC variant
stm32duino/Arduino_Core_STM32 pull request #1375
Opened 2021-04-28 20:19 UTC by owennewo

**Summary**

Adding STORM32_V1_31_RC variantI

I've placed this in the ESC_board menu - technically it is a 3axis gimbal controller (not an ESC) but it can be used as an ESC for smaller motors.

This is a very popular board designed by Olliw (I have no affiliation).
http://www.olliw.eu/storm32bgc-wiki/Main_Page

**Validation**
I've tested this using SimpleFOC library and have most things working
 - SerialUSB, Serial3, I2C1, I2C2
 - Can spin 3 motors 

Here is an example sketch of it in use:
https://gist.github.com/owennewo/68c3de58d3e14b702552f0c149de41b0

2021-04-29 17:27 UTC, fpistm requested changes
Hi @owennewo 
Thanks for your contribution.
Nice first PR moreover you are the first contributor with the new format.
Hope it was not so hard, wiki will be updated soon.

In addition to my comments could you also update the README.md to reference it in the ESC section.
Moreover it is not very clear for me which board STorM32 board you add?
Is it this one ? http://www.olliw.eu/storm32bgc-wiki/STorM32_Boards#STorM32-BGC_v1.3
In that case why `RC` instead of `BGC` ?

Tthank you in advance.

2021-04-29 17:27 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
> +
Missing Header comments
```suggestion
/*
 *******************************************************************************
 * Copyright (c) 2020-2021, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
/*
 * Automatically generated from STM32F103R(C-D-E)Tx.xml
 * CubeMX DB release 6.0.21
 */
```

2021-04-29 17:27 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
> +  {PB_14_ALT1, USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
To save space
```suggestion
  // {PA_1,       USART2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART2_DISABLE)},
  // {PA_12,      USART1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  // {PB_14,      USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  // {PB_14_ALT1, USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
```

2021-04-29 17:27 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
> +  {PB_13_ALT1, USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
```suggestion
  // {PA_0,       USART2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  // {PA_11,      USART1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  // {PB_13,      USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_DISABLE)},
  // {PB_13_ALT1, USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
```

2021-04-29 17:27 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
> +  {PA_15_ALT1, SPI3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
```suggestion
  // {PA_4,       SPI1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_SPI1_DISABLE)},
  // {PA_15,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_SPI1_ENABLE)},
  // {PA_15_ALT1, SPI3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
```

2021-04-29 17:27 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
> +  {PC_11, USART3, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
Note that other way would be to use  `PC11_ALT1` in the variant header
`#define USART3_RX       PC11_ALT1`

```suggestion
  // {PC_11_ALT1, UART4,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, AFIO_NONE)},
  {PC_11,      USART3, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
```

2021-04-29 17:27 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins_STORM32_V1_31_RC.c
> +  {PC_10, USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
Note that other way would be to use PC10_ALT1 in the variant header
`#define USART3_TX       PC10_ALT1`

```suggestion
  // {PC_10_ALT1, UART4,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_NONE)},
  {PC_10,      USART3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_USART3_PARTIAL)},
```

2021-04-30 15:15 UTC, owennewo commented
I've repushed with a README.

Yes that link is correct.  RC refers to STM32F103*RC* which is by far the most common flash size version (and is the one I have), but as this board is open source, people have made RB, RE and RG versions which I've not tested and don't really know whether they'll work.  If you'd prefer me to remove the RC from the name, so that others can later add support for different flash sizes then I can do that.  I can also add BGC (which I think stands for Brushless Gimbal Controller) if you like.

2021-04-30 16:54 UTC, fpistm commented
Thanks for the README.
About the different flash size, in fact it can be managed easily by adding correct boards entry in the boards.txt and renaming the `variant_STORM32_V1_31_RC.*`  and `peripheralPins_STORM32_V1_31_RC.c ` to 
`variant_STORM32_V1_31_Rx.*` and `peripheralPins_STORM32_V1_31_Rx.c `

Then adding in the boards.txt:
+# STORM32_V1_RC board
+ESC_board.menu.pnum.STORM32_V1_31_RC=STorM32 BGC v1.31 RC
+ESC_board.menu.pnum.STORM32_V1_31_RC.upload.maximum_size=262144
+ESC_board.menu.pnum.STORM32_V1_31_RC.upload.maximum_data_size=49152
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.mcu=cortex-m3
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.board=STORM32_V1_31_RC
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.series=STM32F1xx
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.product_line=STM32F103xE
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.peripheral_pins=-DCUSTOM_PERIPHERAL_PINS
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.cmsis_lib_gcc=arm_cortexM3l_math
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.variant=STM32F1xx/F103R(C-D-E)T
+ESC_board.menu.pnum.STORM32_V1_31_RC.build.variant_h=variant_STORM32_V1_31_Rx.h

+# STORM32_V1_RD board
+ESC_board.menu.pnum.STORM32_V1_31_RD=STorM32 BGC v1.31 RD
+ESC_board.menu.pnum.STORM32_V1_31_RD.upload.maximum_size=393216
+ESC_board.menu.pnum.STORM32_V1_31_RD.upload.maximum_data_size=65536
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.mcu=cortex-m3
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.board=STORM32_V1_31_RD
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.series=STM32F1xx
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.product_line=STM32F103xE
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.peripheral_pins=-DCUSTOM_PERIPHERAL_PINS
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.cmsis_lib_gcc=arm_cortexM3l_math
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.variant=STM32F1xx/F103R(C-D-E)T
+ESC_board.menu.pnum.STORM32_V1_31_RD.build.variant_h=variant_STORM32_V1_31_Rx.h

+# STORM32_V1_RE board
+ESC_board.menu.pnum.STORM32_V1_31_RE=STorM32 BGC v1.31 RE
+ESC_board.menu.pnum.STORM32_V1_31_RE.upload.maximum_size=524288
+ESC_board.menu.pnum.STORM32_V1_31_RE.upload.maximum_data_size=65536
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.mcu=cortex-m3
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.board=STORM32_V1_31_RE
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.series=STM32F1xx
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.product_line=STM32F103xE
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.peripheral_pins=-DCUSTOM_PERIPHERAL_PINS
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.cmsis_lib_gcc=arm_cortexM3l_math
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.variant=STM32F1xx/F103R(C-D-E)T
+ESC_board.menu.pnum.STORM32_V1_31_RE.build.variant_h=variant_STORM32_V1_31_Rx.h

And in each files adding the correct switch:
`#if defined(ARDUINO_STORM32_V1_31_RC) || defined(ARDUINO_STORM32_V1_31_RD) || defined(ARDUINO_STORM32_V1_31_RE)`

In fact the linker script is preprocessed so the correct flash and RAM size will be used:
https://github.com/stm32duino/Arduino_Core_STM32/blob/0a3fa54b4a645eba9f9e5db9165a85c3bfc6d66e/variants/STM32F1xx/F103R(C-D-E)T/ldscript.ld#L36-L41

Note that you didn't fix my other review comments.

2021-04-30 18:10 UTC, owennewo commented on boards.txt
> +ESC_board.menu.pnum.STORM32_V1_31_RC.build.extra_flags=-D{build.product_line} {build.enable_usb} {build.xSerial}
Aah! this is why my batch commit (of your suggestions) wouldn't work.  Github us saying
`Suggestion cannot be identical to original text. `

You meant to delete the two lines?

2021-04-30 18:13 UTC, owennewo commented
I'll retest after accepting your changes.  The Serial3/SerialUSB took me a while to get working automatically so this is the area I'm not confident in - perhaps something else is missing in this area.

Regaring RC/RB/RE/RG versions of this board - I think I confused myself and you

RC - exists
RE - only exists in a later variant (3.x which is quite different)
RB and RG are mentioned in this schematic https://community.simplefoc.com/uploads/default/original/1X/6f1cdb4a8d6bfdd6d405aa340ca2571f5be42738.jpeg but I've not seen them for sale.  I don't think they exist!
TLDR: I think we only need single flash size RC

2021-05-03 07:56 UTC, fpistm commented on boards.txt
> +ESC_board.menu.pnum.STORM32_V1_31_RC.build.extra_flags=-D{build.product_line} {build.enable_usb} {build.xSerial}
yes

2021-05-03 08:12 UTC, fpistm commented on README.md
> +| :green_heart:  | STM32F103RCT | [STorM32 V1.31 RC](http://www.olliw.eu/storm32bgc-wiki/STorM32_Boards#STorM32-BGC_v1.3) | *2.0.0* |  |
```suggestion
| :yellow_heart:  | STM32F103RCT | [STorM32 V1.31 RC](http://www.olliw.eu/storm32bgc-wiki/STorM32_Boards#STorM32-BGC_v1.3) | **2.1.0** |  |
```

2021-05-03 08:15 UTC, fpistm commented
OK so we can kept only one variant.


>  The Serial3/SerialUSB took me a while to get working automatically so this is the area I'm not confident in - perhaps something else is missing in this area.

I'm confident 😉

2021-05-03 08:19 UTC, fpistm reviewed
PR LGTM. Only one question about the `HAL_SD_MODULE_ENABLED` .

2021-05-03 08:19 UTC, fpistm commented on variants/STM32F1xx/F103R(C-D-E)T/variant_STORM32_V1_31_RC.h
> +#endif
It seems there is no SD card slot on the board and SDIO pins are used for other stuff. So I think the define could be safely removed.
```suggestion
```

2021-05-03 11:44 UTC, owennewo commented
> OK so we can kept only one variant.
> 
> > The Serial3/SerialUSB took me a while to get working automatically so this is the area I'm not confident in - perhaps something else is missing in this area.
> 
> I'm confident

I found the issue - ESC_board.menu was missing `CDC (generic 'Serial' supersede U(S)ART)` (I was using `CDC (No generic Serial)` )

Hopefully this is ready to merge

2021-05-03 12:41 UTC, fpistm commented on boards.txt
> +ESC_board.menu.xusb.HSFS.build.usb_speed=-DUSE_USB_HS -DUSE_USB_HS_IN_FS
Add missing entry menu. Not needed for this board specifivally but generic for ESC boards menu entry.

```suggestion
ESC_board.menu.xusb.HS=High Speed
ESC_board.menu.xusb.HS.build.usb_speed=-DUSE_USB_HS
ESC_board.menu.xusb.HSFS=High Speed in Full Speed mode
ESC_board.menu.xusb.HSFS.build.usb_speed=-DUSE_USB_HS -DUSE_USB_HS_IN_FS
```

2021-05-03 12:44 UTC, fpistm approved these changes

2021-05-03 12:45 UTC, fpistm commented
> I found the issue - ESC_board.menu was missing `CDC (generic 'Serial' supersede U(S)ART)` (I was using `CDC (No generic Serial)` )

Nice catch I missed that. 🙄 

> 
> Hopefully this is ready to merge

Yes, I've made a small update of USB menu entry.

2021-05-03 14:41 UTC, merged