Stm32 mp1 update v1.5.0
stm32duino/Arduino_Core_STM32 pull request #1576
Opened 2021-11-30 16:14 UTC by ABOSTM

**Summary**
Stm32mp1 Cube update v1.5.0

2021-12-02 09:39 UTC, fpistm requested changes
Maybe OpenAmp MW should be updated as well.

2021-12-02 18:19 UTC, ABOSTM commented on License.md
> +* system/Drivers/STM32XXxx_HAL_Driver folders include the STMicroelectronics HAL Drivers.
Done. I kept "include" because "folders" is plural.

2021-12-02 18:20 UTC, ABOSTM commented
> Maybe OpenAmp MW should be updated as well.

I added:
* a commit to update python scripts to copy OpenAmp Middleware in case of MP1
* a commit with effective OpenAmp Middleware update

2021-12-03 15:50 UTC, fpistm approved these changes

2021-12-03 19:27 UTC, merged