Add support for generic STM32G030F6
stm32duino/Arduino_Core_STM32 pull request #1589
Opened 2021-12-13 02:28 UTC by ademuri

This adds support for generic `STM32G030F6`-based boards. I have a custom board which uses this processor. I partially tested the `CheckVariant` sketch - I verified that the LED blinks slowly, but did not check the serial output.

2021-12-13 08:24 UTC, fpistm commented
Hi @ademuri 
Thanks for the PR, @ABOSTM will review it.
As a first feedback, I would recommend to update the generic clock config.

2021-12-13 14:42 UTC, ABOSTM requested changes
@ademuri
Thanks for this Pull Request. As said @fpistm, it would be better to redefine the generic clock config to benefit from better performances
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)#3---generic-system-clock-configuration
otherwise you stuck on default reset clock (which is slow).

2021-12-15 02:01 UTC, ademuri commented on README.md
> +| :green_heart: | STM32G030F6<br>STM32G030F6 | Generic Board | **2.2.0** |
Done.

2021-12-15 02:02 UTC, ademuri commented
Updated the clock.

2021-12-15 09:41 UTC, ABOSTM requested changes
Almost good.
See inline comment.
Also could you run Astyle to fix CI issue:
https://github.com/stm32duino/wiki/wiki/Astyle

2021-12-15 09:41 UTC, ABOSTM commented on variants/STM32G0xx/G030F6P/generic_clock.c
> +  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
With compiler we used, assignation to 0 on such heterogenous structure causes compiler warning, 
(and are not required) 
```suggestion
    RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
```

2021-12-16 08:45 UTC, fpistm commented on variants/STM32G0xx/G030F6P/generic_clock.c
> +  {
```suggestion
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
```

2021-12-16 08:46 UTC, fpistm commented on variants/STM32G0xx/G030F6P/generic_clock.c
> +  {
```suggestion
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
    Error_Handler();
  }
  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                                 | RCC_CLOCKTYPE_PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) {
```

2021-12-16 11:27 UTC, ABOSTM approved these changes
LGTM

2021-12-16 13:06 UTC, merged

2022-01-17 22:27 UTC, vik0asth commented
Thanks for adding the support for this MCU in latest version. I have a custom board with STM32G0F6Px MCU also. I am trying to run tone example on that but not getting any output/ sound on buzzer.

Same tone example code runs fine on Nucleo-64 STM32G071RB eval board but not on custom board. The "variant_generic.h" files for the two MCUs uses two different timers - could that be the problem? TIM6/TIM7 are not supported on STM32G0F6Px, so which timer to use?

![image](https://user-images.githubusercontent.com/2757091/149842461-f4281938-ef6c-4cb7-a04e-a8a07b7c433e.png)

Can anyone please help to resolve this issue?

Thanks in advance.