Add variant G070RB
stm32duino/Arduino_Core_STM32 pull request #1609
Opened 2021-12-25 11:50 UTC by MrZloHex

## Pull Request template

**Summary**

Adding new variant `G070RBT`

This PR fixes/implements the following **bugs/features**

* [X] New variant for NUCLEO-G070RB
* [ ] Add variant for bare STM32G070RB

New variant will be supported by stm32duino

2022-01-04 15:16 UTC, ABOSTM requested changes
Hi @MrZloHex,
Thanks for this PR.
Few inline comment.
Also could you run Astyle on generic_clock.c:
https://github.com/stm32duino/wiki/wiki/Astyle

2022-01-04 15:16 UTC, ABOSTM commented on README.md
> +| :green_heart: | STM32G070RB | Generic Board | *0.1.0* |  |
```suggestion
| ::yellow_heart:: | STM32G070RB | Generic Board | *2.3.0* |  |
```

2022-01-04 15:16 UTC, ABOSTM commented on variants/STM32G0xx/G070RBT/generic_clock.c
> +  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
With compiler we used, assignation to 0 on such heterogenous structure causes compiler warning,
(and are not required)
```suggestion
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
```

2022-01-04 15:46 UTC, ABOSTM commented
By the way, you can squash the whole in a single commit.

2022-01-05 16:25 UTC, ABOSTM commented
Thanks for the update, could you run Astyle on generic_clock.c:
https://github.com/stm32duino/wiki/wiki/Astyle
This will fix "STM32 Core Continuous Integration" check,
and by the way squash the whole in a single commit.

2022-01-05 21:15 UTC, MrZloHex commented
Ok

2022-01-21 16:06 UTC, fpistm commented
Any update on this PR ?

2022-01-31 11:27 UTC, ABOSTM commented
This PR is superseded by #1638

2022-01-31 11:27 UTC, closed without merging