Added F722RE Variant to boards.txt, added F722RE ldscript.ld
stm32duino/Arduino_Core_STM32 pull request #1712
Opened 2022-05-08 23:06 UTC by geosmall

## Pull Request template

Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:

**Summary**

This PR fixes/implements the following **bugs/features**

* [ ] Bug 1
* [ ] Bug 2
* [ ] Feature 1
* [ ] Feature 2
* [ ] Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Validation**

* Ensure CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]

**Code formatting**

* Ensure AStyle check is passed thanks CI

**Closing issues**

Fixes #xxx

2022-05-08 23:09 UTC, geosmall commented
Add F722RE variant

2022-05-08 23:12 UTC, geosmall commented
Try again to add F722RE variant

2022-05-09 07:43 UTC, fpistm requested changes
Hi  @geosmall 
Thanks for the PR.
Could you add the 3 other mcu boards entries int the boards.txt?
It misses also the update of the README.md.

I guess it should be fine to add a default system core clock config to ensure USB clock is correctly set to 48 MHz in https://github.com/stm32duino/Arduino_Core_STM32/blob/949ecc80d0399b4a5ead733ff57be5f728a47c4d/variants/STM32F7xx/F722R(C-E)T_F730R8T_F732RET/generic_clock.c#L25

2022-05-09 07:43 UTC, fpistm commented on boards.txt
> +# Generic F722RETx
I would add also the 3 other mcu's here:
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32F7xx/F722R(C-E)T_F730R8T_F732RET/boards_entry.txt

2022-05-30 13:13 UTC, fpistm commented
README.md will be updated later else it will add merge conflict:
```patch
+| :yellow_heart: | STM32F722RC<br>STM32F722RE | Generic Board | **2.3.0** |  |
+| :yellow_heart: | STM32F730R8<br>STM32F732RE | Generic Board | **2.3.0** |  |
```

2022-05-31 07:02 UTC, merged