Adding L431RC  Generic
stm32duino/Arduino_Core_STM32 pull request #1736
Opened 2022-06-03 23:51 UTC by mackelec

Adding L431RC generic.
Added  ldscript.ld
Edited  Boards and Readme

2022-06-06 08:48 UTC, ABOSTM requested changes
Thanks @mackelec for this Pull Request.
It would be great if you could also update the generic clock so that users can benefit from 80Mhz (thanks to PLL),  instead of relying on default 4Mhz clock (MSI).
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-%28board%29#3---generic-system-clock-configuration

2022-06-06 08:48 UTC, ABOSTM commented on boards.txt
> +
Would be great if you could add all the generic MCU you can found in boards_entry.txt, as they share the same configuration files (it is just a copy and past of boards_entry.txt, but don't forget to also add them in README.md)

2022-06-06 08:48 UTC, ABOSTM commented on variants/STM32L4xx/L431R(B-C)(I-T-Y)/ldscript.ld
> +  FLASH    (rx)    : ORIGIN = 0x8000000,   LENGTH = 256K
Could you please update .ld file according to wiki:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-%28board%29#3---generic-system-clock-configuration

2022-06-07 02:23 UTC, mackelec commented
Thank you for your review.  I hope I've made all the correct updates this time.

2022-06-07 08:01 UTC, ABOSTM requested changes
@mackelec,
Thanks for this update,
It looks like you kind of revert several merged commit.
I did not list all but there is clearly too much update in board.txt

2022-06-07 08:03 UTC, ABOSTM requested changes

2022-06-07 08:03 UTC, ABOSTM commented on boards.txt
> -# Generic F722RCTx
Looks like revert of PR #1722

2022-06-08 09:42 UTC, ABOSTM requested changes

2022-06-08 12:35 UTC, mackelec commented on README.md
> +| :green_heart:  | STM32L412K8<br>STM32L412KB<br>STM32L422KB | Generic Board | *2.0.0* |  |
I'm sorry Alexandre, I'll look at it tomorrow,

2022-06-16 07:51 UTC, fpistm commented on README.md
> +| :green_heart:  | STM32L431RB<br>STM32L431RC | Generic Board | **2.3.0** |  |
```suggestion
| :yellow_heart:  | STM32L431RB<br>STM32L431RC | Generic Board | **2.3.0** |  |
```

2022-06-21 07:58 UTC, fpistm requested changes

2022-06-21 07:58 UTC, fpistm commented on variants/STM32L4xx/L431R(B-C)(I-T-Y)/ldscript.ld
> +**                      16Kbytes RAM2
This seems wrong based on datasheet:

> Embedded SRAM
> STM32L431xx devices feature 64 Kbyte of embedded SRAM. This SRAM is split into two
> blocks:
> • 48 Kbyte mapped at address 0x2000 0000 (SRAM1)
> • 16 Kbyte located at address 0x1000 0000 with hardware parity check (SRAM2).
> This memory is also mapped at address 0x2000 C000, offering a contiguous address
> space with the SRAM1 (16 Kbyte aliased by bit band)
> This block is accessed through the ICode/DCode buses for maximum performance.
> These 16 Kbyte SRAM can also be retained in Standby mode.
> The SRAM2 can be write-protected with 1 Kbyte granularity.
> The memory can be accessed in read/write at CPU clock speed with 0 wait states.

2022-06-21 07:58 UTC, fpistm commented on variants/STM32L4xx/L431R(B-C)(I-T-Y)/ldscript.ld
> +  RAM2    (xrw)    : ORIGIN = 0x10000000,   LENGTH = 16K
Ditto,
as boards.txt specify 64 k,  RAM2 should not be define or RAM should be 48k

2022-06-21 07:58 UTC, fpistm commented on boards.txt
> +Midatronics.menu.rtlib.full.build.flags.ldspecs=
Don't know why this line is changed?

2022-06-21 14:07 UTC, fpistm approved these changes
LGTM. Thanks @mackelec & @ABOSTM

2022-06-21 14:09 UTC, merged