variant: G0: add Nucleo-G070RB
stm32duino/Arduino_Core_STM32 pull request #1745
Opened 2022-06-20 16:01 UTC by TDhaouST

### **Tested:**
 GPIO

- [ ]  U(S)ART
- [ ]  ADC
- [ ]  DAC
- [ ]  I2C
- [ ]  SPI
- [ ]  Timer
- [ ]  RTC
- [ ]  Low Power
- [ ]  EEPROM

2022-06-20 16:43 UTC, fpistm requested changes
I will deeply reviewed later. Here a first feedback.

2022-06-20 16:43 UTC, fpistm commented on README.md
> +|:green_heart:  | STM32G070RB | [Nucleo G070RB](https://www.st.com/en/evaluation-tools/nucleo-g070rb.html) | *1.6.0* |  |
```suggestion
|  :yellow_heart:  | STM32G070RB | [Nucleo G070RB](https://www.st.com/en/evaluation-tools/nucleo-g070rb.html) | **2.3.0** |  |
```

2022-06-20 16:43 UTC, fpistm commented on README.md
> +| :yellow_heart: | STM32F730R8<br>STM32F732RE | Generic Board | **2.3.0** |  |
This should not be there

```suggestion
```

2022-06-20 16:43 UTC, fpistm commented on variants/STM32G0xx/G070RBT/generic_clock.c
> +  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
This file should not have been modified.

2022-06-21 09:26 UTC, fpistm approved these changes
Thanks for the update.

2022-06-21 09:49 UTC, ABOSTM requested changes
2 minor comments

2022-06-21 09:49 UTC, ABOSTM commented on variants/STM32G0xx/G070RBT/variant_NUCLEO_G070RB.cpp
> +#endif /* ARDUINO_NUCLEO_G071RB */
```suggestion
#endif /* ARDUINO_NUCLEO_G070RB */
```

2022-06-21 09:49 UTC, ABOSTM commented on variants/STM32G0xx/G070RBT/variant_NUCLEO_G070RB.h
> + * Copyright (c) 2021, STMicroelectronics
```suggestion
 * Copyright (c) 2022, STMicroelectronics
```

2022-06-21 09:56 UTC, fpistm requested changes

2022-06-21 09:56 UTC, fpistm commented on variants/STM32G0xx/G070RBT/variant_NUCLEO_G070RB.cpp
> + RCC_OscInitTypeDef RCC_OscInitStruct = {};
astyle issue
```suggestion
  RCC_OscInitTypeDef RCC_OscInitStruct = {};
```

2022-06-21 12:38 UTC, fpistm approved these changes

2022-06-21 12:46 UTC, ABOSTM approved these changes

2022-06-21 14:21 UTC, merged