Print and debug improvements
stm32duino/Arduino_Core_STM32 pull request #1750
Opened 2022-06-24 17:31 UTC by matthijskooijman

**Summary**

This PR makes some changes to the printing/printf code, both in the Print class and in `core_debug`.

The main change that I needed is to add a "v" version of the `core_debug()` function. Like `vprintf` vs `printf`, the `vcore_debug` function does not accept individual arguments to interpolate into format string, but a `va_list` instance. This allows it to be called from another function that is itself a varargs function and forwards its variable arguments.

I originally thought I needed this for `Print::printf`, so I implemented `Print::vprintf` too. I ended up using `core_debug()` instead, but the `vprintf()` implementation might be useful for others (and adds zero code space if unused), so I just added it.

Finally, when looking at the `core_debug()` code, I noticed the function was `static` and declared in a header file, which causes it to potentially take up a lot more flash space than needed, so I fixed that as well. See the commit message for details.

2022-06-27 13:14 UTC, fpistm requested changes
Hi @matthijskooijman 

Thanks for the PR.
You have to move this include outside the `#if !defined(NDEBUG)`
https://github.com/stm32duino/Arduino_Core_STM32/blob/e3f4ee44344866dc5442f653e383a7da14e4db10/cores/arduino/core_debug.h#L5

else it does not built properly when Core logs are not enabled 😉 

And please fix astyle issue.

2022-06-28 13:38 UTC, matthijskooijman commented
Good call, should have tested that. Fixed (and tested ;-p) now.

2022-06-29 15:06 UTC, fpistm approved these changes
Thanks @matthijskooijman for this PR, it LGTM.
About the failed CI, it is not linked to this PR but to an update of the arduino-lint which raised new error/warning. This is fixed thanks #1754.

2022-06-29 16:25 UTC, merged

2022-06-29 19:33 UTC, matthijskooijman commented
Thanks!