Added Generic F3xx Boards
stm32duino/Arduino_Core_STM32 pull request #1795
Opened 2022-08-11 10:39 UTC by alextrical

| :yellow_heart: | STM32F301C6<br>STM32F301C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F301K6<br>STM32F301K8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F301R6<br>STM32F301R8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F303C6<br>STM32F303C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F303R6<br>STM32F303R8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F318C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F318K8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F328C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F334C4<br>STM32F334C6<br>STM32F334C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F334R6<br>STM32F334R8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F358CC | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F358RC | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F358VC | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F378CC | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F378RC | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F378VC | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32F398VE | Generic Board | **2.4.0** |  |

2022-08-11 12:46 UTC, ABOSTM approved these changes
LGTM

2022-08-11 15:16 UTC, ABOSTM requested changes
missing parenthesis in linker files

2022-08-12 15:21 UTC, ABOSTM approved these changes

2022-08-30 09:50 UTC, fpistm approved these changes
LGTM.
Thanks

2022-08-30 12:19 UTC, merged