Added F13-F24 to USB HID.
stm32duino/Arduino_Core_STM32 pull request #1845
Opened 2022-10-08 20:34 UTC by mikaelsundin

Summary:
Adds F13 to F24 to USB HID, make it possible to use KEY F13 to F24 on USB HID keyboard.

```
#include <Keyboard.h>

void setup() {
    Keyboard.begin();
}

void loop() {
   Keyboard.press(KEY_F13);
   delay(100);

   Keyboard.release(KEY_F13);   
   delay(1000);
}
```

2022-10-10 08:09 UTC, fpistm requested changes

2022-10-10 08:09 UTC, fpistm commented on cores/arduino/stm32/usb/hid/usbd_hid_composite.c
> +  0x25, 0x73,       // Logical Maximum(115)
It should be 0x71 as you add 12 keys? 101 + 12 = 113

2022-10-10 08:09 UTC, fpistm commented on cores/arduino/stm32/usb/hid/usbd_hid_composite.c
> +  0x29, 0x73,       // Usage Maximum (115)
ditto

2022-10-10 16:18 UTC, mikaelsundin commented on cores/arduino/stm32/usb/hid/usbd_hid_composite.c
> +  0x29, 0x73,       // Usage Maximum (115)
se above.

2022-10-11 13:52 UTC, fpistm approved these changes
LGTM.
Thanks

2022-10-11 13:52 UTC, merged