Add RAK3172 module
stm32duino/Arduino_Core_STM32 pull request #2005
Opened 2023-04-13 17:40 UTC by Oliv4945

**Summary**

This PR implements RAK3172 module bases on STM32WLE5CCU

As discussed the LoRaWAN repo (https://github.com/stm32duino/STM32LoRaWAN/pull/13) it is cleaner to add it here.  
This is still a draft as I did not update the main Readme because of a question: I created the section `LoRa modules` , but is it correct? If not, should I place it in the `LoRa`  boards instead?

**Validation**

* LoRaWAN works on the module. I did not test the other peripherals like SPI or I2C

2023-04-13 17:45 UTC, fpistm commented
Hi @Oliv4945 
Thanks for this contribution.
Please add it to the LoRa section to avoid adding new one. I will review it tomorrow.

2023-04-14 08:50 UTC, Oliv4945 commented
Thanks @fpistm, I moved it.  
I put a green heart as the "generic WLE5CC" but I saw that you put yellow on the Seeedstudio's E5 module, so please tell me your policy ;)

2023-04-14 08:55 UTC, fpistm commented
> 

Well while the new release including the board is not released I put it in yellow and moved to green when officially released.

2023-04-14 13:07 UTC, fpistm requested changes

2023-04-14 14:36 UTC, Oliv4945 commented
Wow, thanks @fpistm and sorry for the mistakes. I have been mislead by another document with some other errors that I reported to RAK. I agree with all your changes except for PB5: unless I am using the wrong datasheet there is no ADC
![image](https://user-images.githubusercontent.com/6248122/232073649-28f7798e-154a-483b-bc7b-1b9e136b41ab.png)
Is that correct?

I order to avoid any further error also doubled checked the PIN definition with their [RUI BSP](https://github.com/RAKWireless/RAK-STM32-RUI/blob/main/variants/WisDuo_RAK3172_Evaluation_Board/variant.h#L33)

2023-04-14 14:40 UTC, fpistm commented
Oups, you are right. PB5 has no ADC as defined in the generic:
https://github.com/stm32duino/Arduino_Core_STM32/blob/31e562d1d49b608761a211eba832ce200a7a3d1a/variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_generic.h#L28-L38

Please fix.

2023-04-14 16:03 UTC, Oliv4945 commented on variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.cpp
> +  PH_3    // D26 - BOOT0
Fixed in bc8e2506f1f464a0ceac383477b62b3972bb2668

2023-04-14 16:03 UTC, Oliv4945 commented on variants/STM32WLxx/WL54CCU_WL55CCU_WLE4C(8-B-C)U_WLE5C(8-B-C)U/variant_RAK3172_MODULE.cpp
> +  24, // A7,  PB14
Fixed in bc8e2506f1f464a0ceac383477b62b3972bb2668

2023-04-14 16:05 UTC, Oliv4945 commented
Thanks, I applied your patch

2023-04-14 16:08 UTC, Oliv4945 commented
> Could you rebase on top of the main as it seems there are some conflits.

Ok, I just did but I did not saw any conflicts

2023-04-14 16:57 UTC, fpistm commented
You don't rebase you do a merge.
Conflict is always here:

`This branch cannot be rebased due to conflicts`

2023-04-16 06:26 UTC, Oliv4945 commented
Right I am more used to merge sorry :)  
I just rebased and squashed the branch to have cleaner history.

2023-04-17 07:08 UTC, fpistm approved these changes
Thanks @Oliv4945 
LGTM. Nice contribution

2023-04-17 07:10 UTC, merged