add STM32L433RC, STM32L433RB and STM32L443RC support
stm32duino/Arduino_Core_STM32 pull request #2033
Opened 2023-06-02 17:35 UTC by emoninet2

## Support for STM32L433RC, STM32L433RB and STM32L443RC

2023-06-03 12:38 UTC, emoninet2 commented
I see there are a few Astyle errors. Do I create a new pull request with the errors fixed?

2023-06-03 12:44 UTC, fpistm commented
> I see there are a few Astyle errors. Do I create a new pull request with the errors fixed?

Hi @emoninet2.  Thanks for this PR. No, simply  amend your commit with astyle fixes and force push on the same branch. Then this PR will be automatically updated.

2023-06-05 08:09 UTC, fpistm requested changes
Thanks for the update.
Still one format issue.
I've also added the USB clock selection else USB will not work as it require 48MHz clock source.

2023-06-05 08:09 UTC, fpistm commented on variants/STM32L4xx/L433R(B-C)(I-T-Y)_L443RC(I-T-Y)/generic_clock.c
> +  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
```suggestion
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {};
```

2023-06-05 08:14 UTC, fpistm approved these changes

2023-06-06 06:38 UTC, merged