Add variant: NUCLEO-H503RB.
stm32duino/Arduino_Core_STM32 pull request #2092
Opened 2023-08-05 17:47 UTC by dojyorin

## Add variant: NUCLEO-H503RB
### Summary
This PR fixes/implements the following **bugs/features**

- Add new variant [`NUCLEO-H503RB`](https://www.st.com/ja/evaluation-tools/nucleo-h503rb.html)

@fpistm feat adds [STM32H5](https://github.com/stm32duino/Arduino_Core_STM32/issues/1978) core implementation and NUCLEO-H563ZI support (That was really great help! Thank you!), but variant support is still lacking.

This time, I'll add new H5 NUCLEO board NUCLEO-H503RB with this pull request.
Related to https://github.com/stm32duino/Arduino_Core_STM32/issues/722#issuecomment-1594863252 and https://github.com/stm32duino/Arduino_Core_STM32/pull/2091

### Progress
There's still some work to do.

- [ ] Adapt [variant_NUCLEO_H503RB.cpp](https://github.com/dojyorin/Arduino_Core_STM32/blob/936a8cc34cfb0f4fe50aab90b020f264143ad993/variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp#L18) and [variant_NUCLEO_H503RB.h](https://github.com/dojyorin/Arduino_Core_STM32/blob/936a8cc34cfb0f4fe50aab90b020f264143ad993/variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h#L18) pin assignments to actual board values.
- [ ] Regarding [peripheral clock](https://github.com/dojyorin/Arduino_Core_STM32/blob/936a8cc34cfb0f4fe50aab90b020f264143ad993/variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp#L161) supply, there are no definitions for commonly used peripherals such as I2C or SPI, is it already defined elsewhere?
- [ ] There any other missing parts?

Basically implementation of NUCLEO-H563ZI is used reference.

I'm new to STM32, so excuse me if I'm doing something wrong.
I would like to discuss with everyone and produce good results.

2023-08-05 18:15 UTC, fpistm commented
Thanks for squashing.  Anyway simply force update on the same branch will avoid creating new PR. :wink : Let ci run to check this PR first.

2023-08-07 08:09 UTC, fpistm requested changes
First thanks for this PR.
In addition to my comments, could you add the generic and the Nucleo in the README.md and also declare them to the boards.txt.
Finally, split in 2 commit, 1 for the generic addition and one for the dedicated Nucleo board.

You can refers to this PR as example:
https://github.com/stm32duino/Arduino_Core_STM32/pull/1859

2023-08-07 08:09 UTC, fpistm commented on variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h
> +  #define LED_BUILTIN           PNUM_NOT_DEFINED
Should be defined to the pin number of the LED

2023-08-07 08:09 UTC, fpistm commented on variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h
> +  #define USER_BTN              PNUM_NOT_DEFINED
Should be defined to the pin number of the user button (blue button)

2023-08-07 08:09 UTC, fpistm commented on variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h
> +#endif
When pin properly ordered no need to define this as by default they are mapped to D10-D13 (SPI) and D14/D15 (I2C)

2023-08-07 08:09 UTC, fpistm commented on variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.h
> +#endif
Did you check the STLink VCP are connected to this U(S)ART pins

2023-08-07 08:09 UTC, fpistm commented on variants/STM32H5xx/H503RBT/generic_clock.c
> +WEAK void SystemClock_Config(void) {
Astyle fix
```suggestion
WEAK void SystemClock_Config(void)
{
```

2023-08-07 08:09 UTC, fpistm commented on variants/STM32H5xx/H503RBT/variant_NUCLEO_H503RB.cpp
> +WEAK void SystemClock_Config(void) {
Astyle fix
```suggestion
WEAK void SystemClock_Config(void)
{
```

2023-08-09 06:44 UTC, dojyorin commented
OK, I understand the coding conventions.
I'll try to work on it over the weekend.

2023-08-14 11:12 UTC, dojyorin commented
Thank you for detailed explanation, it really helped me.
It was a great reference when I wanted to add other boards in the future.

For the time being, I've fixed the part you told me, so I'll commit it.

2023-08-15 07:55 UTC, dojyorin commented
The Arduino pinout only goes up to `D15`/`A5`, but the MCU has more pins.
I wasn't sure what rules to define the "surplus `D16`/`A6` and beyond" pins.

2023-08-28 16:26 UTC, fpistm commented
Hi @dojyorin 
I've reworked and fixed your PR.
Could you try it and force update to your branch. Thanks

2023-08-30 15:21 UTC, closed without merging