Add variant: add support for generic F446Z(C-E)(H-J-T) and Nucleo-F446ZE
stm32duino/Arduino_Core_STM32 pull request #2108
Opened 2023-08-20 09:17 UTC by CMGeldenhuys

**Summary**

This PR adds support for the STM32F446Z(C-E)(H-J-T) variants as well as the Nucleo-F446ZE board. The code has been tested on a Nucleo-F446ZE.

**Closing issues**

Closes #1487 (Already marked as closed, but no support was added, from what I can see.)

2023-08-28 09:50 UTC, fpistm requested changes
Hi @CMGeldenhuys 
Thanks for this PR.
Sorry  for the delay, I was on vacation.
First quick review. Let's CI run to see if any errors occurs.

2023-08-28 09:50 UTC, fpistm commented on README.md
> +| :yellow_heart:  | STM32F446ZE | [Nucleo F446ZE](http://www.st.com/en/evaluation-tools/nucleo-f446ze.html) | *2.7.0* |  |
```suggestion
| :yellow_heart:  | STM32F446ZE | [Nucleo F446ZE](http://www.st.com/en/evaluation-tools/nucleo-f446ze.html) | **2.7.0** |  |
```

2023-08-28 09:50 UTC, fpistm commented on README.md
>  | :green_heart: | STM32F446VC<br>STM32F446VE | Generic Board | **2.0.0** |
```suggestion
| :green_heart: | STM32F446VC<br>STM32F446VE | Generic Board | *2.0.0* |
| :yellow_heart:  | STM32F446ZC<br>STM32F446ZE | Generic Board | **2.7.0** |  |
```

2023-08-30 08:41 UTC, CMGeldenhuys commented
Hi @fpistm, I've updated the README as requested and squashed the changes into the old commits.

2023-08-31 07:51 UTC, merged