Adding support for stm32c011j4m6 (j4/j6XX should be supported but unt…
stm32duino/Arduino_Core_STM32 pull request #2359
Opened 2024-05-05 05:48 UTC by alexnagelberg

…ested)

## Pull Request template

Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:

**Summary**

This PR fixes/implements the following **bugs/features**

* [ ] Adds C011J(4-6)Mxx variants

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Validation**

* Ensure CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]

**Code formatting**

* Ensure AStyle check is passed thanks CI

**Closing issues**

Fixes #xxx

2024-05-06 07:15 UTC, fpistm requested changes
Hi @alexnagelberg 
Thanks for this PR.
Could you update tour PR to reference the new generic in the README.md and add a generic clock using LL API (you can use STM32CubeMx to generate it).
Plus a small update of the ldscript to be generic.
Here an example: https://github.com/stm32duino/Arduino_Core_STM32/pull/2048/files

2024-05-06 07:15 UTC, fpistm commented on variants/STM32C0xx/C011J(4-6)M/ldscript.ld
> +  FLASH    (rx)    : ORIGIN = 0x8000000,   LENGTH = 16K
```suggestion
  RAM    (xrw)    : ORIGIN = 0x20000000,   LENGTH = LD_MAX_DATA_SIZE
  FLASH    (rx)    : ORIGIN = 0x8000000+ LD_FLASH_OFFSET, LENGTH = LD_MAX_SIZE - LD_FLASH_OFFSET
```

2024-05-06 13:43 UTC, alexnagelberg commented
> Hi @alexnagelberg 
> 
> Thanks for this PR.
> 
> Could you update tour PR to reference the new generic in the README.md and add a generic clock using LL API (you can use STM32CubeMx to generate it).
> 
> Plus a small update of the ldscript to be generic.
> 
> Here an example: https://github.com/stm32duino/Arduino_Core_STM32/pull/2048/files

@fpistm Sure, although this ldscript was generated by cubemx, so I'm not sure how to get it to include but will play around. Just a heads up that this PR is not ready so I put it in draft, mostly as a reminder to myself to finish it.

2024-05-06 21:11 UTC, alexnagelberg commented
Added remaining changes. Still in testing with my new chip.

2024-05-07 06:53 UTC, fpistm requested changes
Some minor update to avoid astyle issue.

2024-05-07 06:53 UTC, fpistm commented on README.md
> +| :yellow_heart: | STM32C011J4<br>STM32C011J6 | Generic Board | **2.7.1** |  |
```suggestion
| :yellow_heart: | STM32C011J4<br>STM32C011J6 | Generic Board | **2.8.0** |  |
```

2024-05-07 06:53 UTC, fpistm commented on variants/STM32C0xx/C011J(4-6)M/generic_clock.c
> +void SystemClock_Config(void)
Keep it WEAK to allow redefinition if needed
```suggestion
WEAK void SystemClock_Config(void)
```

2024-05-07 06:53 UTC, fpistm commented on variants/STM32C0xx/C011J(4-6)M/generic_clock.c
> +  {
```suggestion
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
```

2024-05-07 06:53 UTC, fpistm commented on variants/STM32C0xx/C011J(4-6)M/generic_clock.c
> +                              |RCC_CLOCKTYPE_PCLK1;
```suggestion
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1;
```

2024-05-07 06:53 UTC, fpistm commented on variants/STM32C0xx/C011J(4-6)M/generic_clock.c
> +  {
```suggestion
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK) {
```

2024-05-13 12:21 UTC, fpistm commented
Pins defined in the variant generic have no link with the built-in bootloader. Generic files could not be changed as they are automatically generated.

2024-05-13 12:22 UTC, fpistm approved these changes
LGTM

2024-05-13 13:19 UTC, fpistm commented
@alexnagelberg If it is ok for you I will merge the PR.

2024-05-13 13:54 UTC, alexnagelberg commented
> @alexnagelberg If it is ok for you I will merge the PR.

@fpistm Serial doesn't appear to be setup correctly but everything else appears working. I'm okay with it being merged and staying yellow heart.

2024-05-13 14:02 UTC, fpistm commented
> Serial doesn't appear to be setup correctly

The only thing which could avoid serial to work is a wrong clock config anyway on C0 clock tree is not complicated so it should basically work.

2024-05-27 09:46 UTC, fpistm commented
> > Serial doesn't appear to be setup correctly
> 
> The only thing which could avoid serial to work is a wrong clock config anyway on C0 clock tree is not complicated so it should basically work. What is the issue? wrong speed ? ...

Looking at the package, by default Serial is mapped on USART1 Using PA0 and PA1 but they are both on the same pin. So to test you can try to redefine the RX on PC14 before calling `begin()`

`Serial.setRx(PC14);`

2024-05-27 13:04 UTC, fpistm commented
I've squash you PR and update the clock config to use LL instead of HAL. This allows to save 1K flash.

2024-05-27 13:23 UTC, fpistm commented
Codespell issue can be safely ignored (see #2379).

2024-05-27 13:23 UTC, fpistm approved these changes

2024-05-28 07:17 UTC, merged