Added Support for ELV-BM-TRX1
stm32duino/Arduino_Core_STM32 pull request #2373
Opened 2024-05-22 06:36 UTC by ELV-Elektronik-AG

## Pull Request template

Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:

**Summary**

This PR fixes/implements the following **bugs/features**

* [ ] Added Support for the ELV-BM-TRX1

The ELV Modular System is a great fit for the stm32duino library

**Validation**

Github Actions have passed, a working sketch is 

```
#include "STM32LowPower.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  // Configure low power
  LowPower.begin();
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  LowPower.deepSleep(1000);
  digitalWrite(LED_BUILTIN, LOW);
  LowPower.deepSleep(1000);
}
```

2024-05-23 09:32 UTC, fpistm commented
Hi @ELV-Elektronik-AG 
I've made some change on your PR. (Note: as a good practice I advise to not use main branch name for a PR).
I've removed all commented code, fix some change in the README.d not link to the PR and fixed the boards.txt.
Anyway I've some other questions I will raised in the review.

2024-05-23 09:44 UTC, fpistm requested changes

2024-05-23 11:57 UTC, fabry1992 commented on boards.txt
> +ELV_Modular_System.menu.pnum.ELV_BM_TRX1.upload.maximum_data_size=16383
Thank you for bringing this up. you are correct, the values are from another linker file where there is space alocated for an EEprom simulation. Your Suggestions are the correct values

2024-05-23 12:01 UTC, fabry1992 commented on variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.h
> +#define NUM_ANALOG_INPUTS       12
Hi, thanks for the offer to help us out. I have revised the Pin Definitions as follows:

```
#define PB12                     0
#define PA0                     1
#define PB14                    PIN_A0
#define PC14                    3
#define PA9                     4
#define PA10                     5
#define PA11                    6
#define PA12                    7
// J1
#define PA14                     PIN_A1
#define PA13                     PIN_A2
#define PA2                     10
#define PA3                     11
#define PA4                     12
#define PA5                     13
#define PA6                    14
#define PA7                    15

// Not on connectors
#define PA15                     16     
#define PB3                     17
// #define PC3                     18
#define PC4                     19
#define PC5                     20


// Alternate pins number
#define PA1_ALT1                (PA1 | ALT1)
#define PA2_ALT1                (PA2 | ALT1)
#define PA3_ALT1                (PA3 | ALT1)
#define PA7_ALT1                (PA7 | ALT1)
#define PB8_ALT1                (PB8 | ALT1)
#define PB9_ALT1                (PB9 | ALT1)

#define NUM_DIGITAL_PINS        21
#define NUM_ANALOG_INPUTS       3
```

I am Still new at the github Open source thing, can you point me in the right direction where i can correctly submit this code to amend the PR?

2024-05-23 12:02 UTC, fabry1992 commented on variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.cpp
> +  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_MSI;
It has both, a 32MHz HSE and a 32768 Hz LSE

2024-05-23 12:04 UTC, fabry1992 commented on variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.cpp
> +  30  // A11, PB14
I have amended the Pin definitions:

```
// Digital PinName array
const PinName digitalPin[] = {
// J2
  PB_12,  // D0
  PA_0,  // D1
  PB_14, // D2
  PC_13,  // D3/A6
  PA_9,  // D4
  PA_10,  // D5
  PA_11, // D6
  PA_12,  // D7
// J1
  PA_14,  // D8
  PA_13,  // D9
  PA_2,  // D10
  PA_3,  // D11
  PA_4,  // D12
  PA_5,  // D13
  PA_6, // D14/A7
  PA_7, // D14/A7
// Not on connectors
  PA_15,
  PB_3,
  // PC_3,
  PC_4,
  PC_5,
  
};

// Analog (Ax) pin number array
const uint32_t analogInputPin[] = {
  2, // A0,  PB1
  8, // A1,  PB2
  9, // A2,  PA10
};
```

2024-05-23 12:11 UTC, fpistm commented on variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.h
> +#define NUM_ANALOG_INPUTS       12
Simply amend your commit or add new one then force push on the same branch. This will automatically update this PR

2024-05-23 12:13 UTC, fpistm commented on variants/STM32WLxx/WL54JCI_WL55JCI_WLE4J(8-B-C)I_WLE5J(8-B-C)I/variant_ELV_BM_TRX1.h
> +#define NUM_ANALOG_INPUTS       12
I recommend to set D0 to a pin not on connector as the silkscreen start from 1. Than PB12 will match 1.

2024-05-23 12:34 UTC, fpistm requested changes

2024-05-23 12:34 UTC, fpistm commented on boards.txt
> +ELV_Modular_System.xserial.disabled.build.xSerial=
`.menu` is missing causing cmake ci to fail.
```suggestion
ELV_Modular_System.menu.xserial.generic=Enabled (generic 'Serial')
ELV_Modular_System.menu.xserial.none=Enabled (no generic 'Serial')
ELV_Modular_System.menu.xserial.none.build.xSerial=-DHAL_UART_MODULE_ENABLED -DHWSERIAL_NONE
ELV_Modular_System.menu.xserial.disabled=Disabled (no Serial support)
ELV_Modular_System.menu.xserial.disabled.build.xSerial=
```

2024-05-23 12:40 UTC, fabry1992 approved these changes

2024-05-23 12:59 UTC, fabry1992 approved these changes

2024-05-23 14:39 UTC, fpistm commented
@ELV-Elektronik-AG, @fabry1992 
I've made the full update, forced pushed on your branch and resolve all conversations.
Please fetch your main branch to get the latest update and check if it is ok.

2024-05-24 11:48 UTC, fabry1992 approved these changes
I hvae tested The pins and everything works. Thanks so much for your work and im sorry to be suc a nuisance

2024-05-24 11:52 UTC, fpistm approved these changes

2024-05-24 12:08 UTC, fpistm commented
Hi @fabry1992 
> I hvae tested The pins and everything works. Thanks so much for your work and im sorry to be suc a nuisance

No worry. Thanks for the test. From my side it is ok to merge. Are you ok?

2024-05-27 09:36 UTC, merged