Add variant: H503KBU
stm32duino/Arduino_Core_STM32 pull request #2423
Opened 2024-07-06 22:32 UTC by dojyorin

I'm sorry for inconvenience caused with PR:Nucleo-H503RB.
Could you please make sure added and modified code?

I set clock settings in STM32CubeMX as described on Wiki, but peripheral settings were not present in code.
(Example: PeriphClkInitStruct.UsbClockSelection = RCC_USBCLKSOURCE_HSI48)
Looking at CubeMX clock settings GUI, for example, USB uses HSI48 by default, so does that mean no additional settings are required?

## Pull Request template

Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:

**Summary**

This PR fixes/implements the following **bugs/features**

* [x] New variant: STM32H503KBU

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Validation**

* Ensure CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]

**Code formatting**

* Ensure AStyle check is passed thanks CI

**Closing issues**

Fixes #xxx

2024-07-08 08:54 UTC, fpistm requested changes
Minor typo to fix and it is ok for me.
About Periphjeral clock config, no need to specify it as HSI48 is the default entry.

2024-07-08 08:54 UTC, fpistm commented on README.md
> +| :yellow_heart:  | STM32H503KB | Generic Board | *2.9.0* |  |
```suggestion
| :yellow_heart:  | STM32H503KB | Generic Board | **2.8.1** |  |
```

2024-07-08 17:51 UTC, dojyorin commented
> About Periphjeral clock config, no need to specify it as HSI48 is the default entry.

Thank you for teaching me.
Version fix suggestion was accepted.

2024-07-09 07:13 UTC, fpistm approved these changes
LGTM

2024-07-09 07:14 UTC, merged